---
title: "Young-ISA Abstract"
author: "Aidan Boland"
date: "9/25/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Statistician or Data Sciencist?


<!-- Data Science is the buzzword. As statisticians we need to adapt to be able to  -->

<!-- This sometimes involves learning skills from other disciplines.  -->

<!-- In [2012, Harvard Business Review](https://hbr.org/2012/10/data-scientist-the-sexiest-job-of-the-21st-century) published an article saying that Data Scientist is the sexiest job of the 21st century. -->
In [2017, The Economist](https://www.economist.com/leaders/2017/05/06/the-worlds-most-valuable-resource-is-no-longer-oil-but-data) published an article saying that the worlds most valuable resource is no longer oil but data, and while this is not a perfect analogy it does highlight the importance of data.  
However, data is only useful if analysed appropriately, and as statisticians, we are more than familiar with the importance of this. The demand for knowledge in statistics is constantly growing in industry.  
This may not be immediately evident as the terminology evolves and broadens; a statistician using linear regression is often referred to as a data scientist using machine learning.
<!-- the base skills have remained much the same. -->

The title data scientist tends to be very broad and can vary substantially across different organisations. Thus, data scientists can have different skill sets. There is a focus on not only being able to apply statistical techniques in once off analysis, but also to implement algorithms inside large production workflows. The focus on presentation and accessibility is also important, and tools such as RMarkdown and Shiny have enabled statisticians to easily share work. It is now reasonably straight forward to build a user interface or to create an interactive presentation both of which can be used to share analysis.

My talk will focus on my journey in industry, what I have learned along the way, and where I see the current role of statisticians in the world of data. I will also present a few examples of ‘data science’ in action.




<!-- As statisticians analysing data is our bread and butter, our techniques are key to getting value from data -->
<!-- In a time where simple linear regression is marketed as machine learning, the demand for knowledge in statistics is greater than ever -->




